mashup/config/routes.rb
Mashup::Application.routes.draw do
  
  resources :students
  resources :entrepreneurs
  resources :sessions, only: [:new, :create, :destroy]
  root 'logins#home'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/supdatepwd',  to: 'students#updatepwd',            via: 'get'
  match '/eupdatepwd',  to: 'entrepreneurs#updatepwd',            via: 'get'
  resource :login do
    member do
      get 'callback'
      get 'logout'
    end
  end

  

end

mashup/app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top"">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Mashup", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <% if signed_in? || lcurrent_user %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <% if user_type=="Student" %>
                <li><%= link_to "Update Profile", edit_student_path(current_user) %></li>
                <li><%= link_to "Update Password", "/supdatepwd" %></li>
                <% else %>
                <li><%= link_to "Update Password", "/eupdatepwd" %></li>
                <% end %>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", logout_login_path, :method => :get  %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", "/login" %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

mashup/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mashup</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    </div>

<%= yield %>

</body>
</html>