mashup/config/routes.rb
Mashup::Application.routes.draw do
  
  resources :students
  resources :entrepreneurs
  resources :sessions, only: [:new, :create, :destroy]
  root 'logins#home'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/supdatepwd',  to: 'students#updatepwd',            via: 'get'
  match '/eupdatepwd',  to: 'entrepreneurs#updatepwd',            via: 'get'
  resource :login do
    member do
      get 'callback'
      get 'logout'
    end
  end

  

end

mashup/app/models/entrepreneur.rb
class Entrepreneur < ActiveRecord::Base
   before_save { self.email = email.downcase }
   validates :fname, presence: true, length: { maximum: 20 }
   validates :lname, presence: true, length: { maximum: 20 }
   VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
   validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
   has_secure_password
   validates :password, length: { minimum: 6 }

   def Entrepreneur.new_remember_token
    SecureRandom.urlsafe_base64
   end

   def Entrepreneur.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
   end

  private

   def create_remember_token
     self.remember_token = Entrepreneur.encrypt(Entrepreneur.new_remember_token)
   end
end

mashup/app/controllers/entrepreneurs_controller.rb
class EntrepreneursController < ApplicationController
  def new
   @user = Entrepreneur.new
   store_location
  end

  def show
    @user = Entrepreneur.find(params[:id])
  end

  def updatepwd
    @user = current_user
  end

  def create
    @entrepreneur = Entrepreneur.new(user_params)
    @user=Users.new
    if @entrepreneur.save
      # Handle a successful save.
      
      if lcurrent_user
         @string=current_user['siteStandardProfileRequest']['url'].scan(/id=+(\d+)/)[0][0]
         @entrepreneur.update_attribute(:linkedin_id,@string)
         @user.update_attribute(:linkedin_id,@string)
      end
      @user.update_attribute(:email,@entrepreneur.email)
      @user.update_attribute(:type,"Entrepreneur")
      @user.save
      sign_in(@entrepreneur,"Entrepreneur")
      flash[:success] = "Welcome to Mashup!!!"
      redirect_to @entrepreneur
    else
      #redirect_back_or "/login"
      render 'new'
    end
  end

  def update
    @user = Entrepreneur.find(params[:id])
    if @user.update_attributes(user_params)
      # Handle a successful update.
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

    def user_params
      params.require(:entrepreneur).permit(:fname, :lname, :email,:password,:password_confirmation)
    end
end

mashup/app/helpers/entrepreneurs_helper.rb
module EntrepreneursHelper
end

mashup/app/views/entrepreneurs/new.html.erb
<% provide(:title, 'Sign up') %>
<% if lcurrent_user %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    </div>

      <%= f.label :fname %>
      <%= f.text_field :fname %>

      <%= f.label :lname %>
      <%= f.text_field :lname %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Reenter Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>
<% else %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    </div>

      <%= f.label :fname %>
      <%= f.text_field :fname %>

      <%= f.label :lname %>
      <%= f.text_field :lname %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Reenter Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>
 <h2>or</h2>
  Sign Up with LinkedIn
  <%=button_to "Sign Up", login_path, :method => :post %>
<% end %>

mashup/app/views/entrepreneurs/show.html.erb
<%= @user.email %><br>

mashup/app/views/entrepreneurs/updatepwd.html.erb
<% provide(:title, "Update Password") %>
<h1>Update your Password</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

  </div>
</div>